FROM node:18.18.0-alpine

ENV APP_ROOT /var/www

ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP.UTF-8
ENV TZ=Asia/Tokyo    

RUN apk update && \
  apk add git bash curl musl musl-utils musl-locales tzdata && \
  npm i -g @nestjs/cli

WORKDIR $APP_ROOT

COPY . $APP_ROOT
